### ISSUE TITLE
TJpgDec R0.02a has been released

### ISSUE THREAD

**Issue by cmumford** [lvgl/lv_lib_split_jpg#14]
This project is still using TJpgDec R0.01d, but R0.02a was released July 11, 2021. http://elm-chan.org/fsw/tjpgd/00index.html

**Comment by kisvegabor** [comment]
In [your repo](https://github.com/cmumford/TJpgDec) have you used this latest version?

**Comment by cmumford** [comment]
Yes. My [upstream ](https://github.com/cmumford/TJpgDec/tree/upstream) branch contains the TJpgDec stream w/o changes. I've [tagged ](https://github.com/cmumford/TJpgDec/tags) that branch for each revision official release. My [master](https://github.com/cmumford/TJpgDec) branch contains my bug fixes and that is what I use in my project. It is upgraded to R0.02a, and was fuzzed on Ubuntu and seems to be as safe as R0.01d.

**Comment by kisvegabor** [comment]
Ah, great! Thank you.

I see no reason why we shouldn't use your updated version but let's tackle down the [ASAN issue](https://github.com/lvgl/lv_lib_split_jpg/issues/12) first.

**Comment by kisvegabor** [comment]
Closed as there is a newer version.
See https://github.com/lvgl/lv_lib_split_jpg/issues/16
