### ISSUE TITLE
TJpgDec R0.03 has been released

### ISSUE THREAD

**Issue by cmumford** [lvgl/lv_lib_split_jpg#16]
TJpgDec R0.03 was released July 1, 2021 and is available at http://elm-chan.org/fsw/tjpgd/00index.html.

I tested this on desktop, and seems as stable as the prior releases. Upgrading to R0.02a was discussed in https://github.com/lvgl/lv_lib_split_jpg/issues/14, but @kisvegabor wanted to fix https://github.com/lvgl/lv_lib_split_jpg/issues/12 (ASAN issue) first. I think we can close https://github.com/lvgl/lv_lib_split_jpg/issues/14 and target an upgrade to R0.03.

**Comment by kisvegabor** [comment]
Sure, we should use the latest and stable version.

**Comment by cmumford** [comment]
Now that the memory bug fix has landed in https://github.com/lvgl/lv_lib_split_jpg/pull/17 I will create a new PR to upgrade TJpgDec to R0.03.

**Comment by kisvegabor** [comment]
Great, thanks!

**Comment by kisvegabor** [comment]
I've pushed some updates for the file system part to make it work again with v8. 
See 5de9fd9
