### ISSUE TITLE
Use lv_fs function

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lv_lib_split_jpg#2]
Now `fopen` and similar functions are used but it'd be more flexible if `lv_fs_...` functions were used here too.

@vinodstanur, will you have time to deal with it?

**Comment by vinodstanur** [comment]
Hi @kisvegabor , moved it to lv_fs and added jpg support alongside with sjpg.

**Comment by kisvegabor** [comment]
Already added so I close this issue.
Thanks @vinodstanur
