### ISSUE TITLE
Crash while read jpg from SD card

### ISSUE THREAD

**Issue by ifengchao** [lvgl/lv_lib_split_jpg#33]
Platform: ESP32 & lvgl 8.3.3

Example code:
`void setup(){
    sd.init();
    lv_init();
    lv_fs_fatfs_init();
    lv_split_jpeg_init();
}

void ui_s1_screen_init(void)
{
    ui_s1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_s1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_s1bg = lv_img_create(ui_s1);
    lv_img_set_src(ui_s1bg, "S:/image/small_image.jpg");
}`

Crash log:
  #0  0x400e8202:0x3ffb25a0 in input_func at lib/lvgl-v8.3/src/extra/libs/sjpg/lv_sjpg.c:306
  #1  0x400d54d6:0x3ffb25d0 in jd_prepare at .pio/libdeps/bigtvlite/TJpg_Decoder/src/tjpgd.c:1001
  #2  0x400e8507:0x3ffb2610 in decoder_info at lib/lvgl-v8.3/src/extra/libs/sjpg/lv_sjpg.c:267
  #3  0x400e7e9e:0x3ffb2710 in lv_img_decoder_get_info at lib/lvgl-v8.3/src/draw/lv_img_decoder.c:99
  #4  0x400f5c87:0x3ffb2730 in lv_img_set_src at lib/lvgl-v8.3/src/widgets/lv_img.c:107
  #5  0x400d300f:0x3ffb2770 in ui_s1_screen_init at src/ui.c:144

Things i tried:
1. Replace with small jpg file.
2. SD api works fine, like list dir etc.

Regards, ifeng

**Comment by kisvegabor** [comment]
Please attache the image you have used.

**Comment by ifengchao** [comment]
> 
![small_image](https://user-images.githubusercontent.com/1748409/206179414-cfdf674e-4e49-45de-ad0e-74205961d615.jpg)

I have tried different jpg images without success. Thank you.

**Comment by kisvegabor** [comment]
Please enable the [logging of LVGL](https://docs.lvgl.io/master/porting/log.html) to see if it reports any issues.

It can be an out of memory issue, which will be shown in the logs.

**Comment by ifengchao** [comment]
Find the problem, this lib may conflict with lib Tjpg_Decoder, they were both in my one project, see from the log, i think the compiler mixed with file TJpg_Decoder/src/tjpgd.c

#1 0x400d54d6:0x3ffb25d0 in jd_prepare at .pio/libdeps/bigtvlite/TJpg_Decoder/src/tjpgd.c:1001

I removed the Tjpg_Decoder, the problem disappeared.

Thank you @kisvegabor , i'll close the issue.
