### ISSUE TITLE
Failed to use lv_img_set_zoom  

### ISSUE THREAD

**Issue by coollqj** [lvgl/lv_lib_split_jpg#4]
Hello, I have successfully used the current  library, and the device shows that JPEG is normal, but I cannot use LV_IMG_SET_ZOOM to scale my JPEG picture, is there any way to solve the scaling of JPEG?

**Comment by embeddedt** [comment]
https://docs.lvgl.io/latest/en/html/widgets/img.html#transformations

> transformations work only on true color images stored as C array, or if a custom Image decoder returns the whole image.

I am pretty sure that this decoder does not return the whole image in one pass, so you will be unable to scale the JPEG. If you need this feature you will have to use the C array method.

**Comment by kisvegabor** [comment]
As the question is answered I close this issue.
