### ISSUE TITLE
JPG on esp32

### ISSUE THREAD

**Issue by beckmx** [lvgl/lv_lib_split_jpg#6]
Hello guys, I was testing the library on platformio, I noticed that it didnt have the arduino scheme, but anyway I managed to run it under platformio, some minor changes but it did compile at the end. I also setup the lv_fs_if but here is where my doubt comes, I included the 

`#define LV_USE_FS_IF	1`

At the end of the _lv_conf.h_ but my guess is that it doesnt have the SPIFFS support, right?, I would have to manually create the implementation? 

My current behaviour is that, some of the elements of the screen are rendered but the space where the image should go is left blank

**Comment by beckmx** [comment]
closing as looks not related to this particular repo

**Comment by embeddedt** [comment]
> my guess is that it doesnt have the SPIFFS support, right?

That's right; currently `lv_fs_if` only supports ChaN's FatFs library and the POSIX file APIs.
